name: Unit Testing

env:
  python.version: 3.8
  python.venv: 'testvenv'

on:
  push:
    branches: [ main ]
    tags:
     - 'v*'
     - v*
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: 'Build and validate source distribution'
        run: |
          python setup.py sdist
          python -m pip install twine
          python -m twine check dist/*

      - name: 'Unit testing'
        run: | 
          pytest -v --cov=pytest-azurepipelines --cov=tests --cov-config=.coveragerc -cov-report=xml --junitxml=junit/test-results.xml tests -p no:faulthandler
    
      - name: "Build and upload to PyPI"
        if: startsWith(github.ref, 'refs/tags')
        run: |
          python setup.py sdist
          python -m twine upload --skip-existing dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
